// Generated code
#[macro_export]
#[doc(hidden)]
macro_rules! __generated_char_reexports {
    () => {
        pub use super::albedo::*;
        pub use super::amber::*;
        pub use super::arataki_itto::*;
        pub use super::barbara::*;
        pub use super::beidou::*;
        pub use super::bennett::*;
        pub use super::candace::*;
        pub use super::chongyun::*;
        pub use super::collei::*;
        pub use super::cyno::*;
        pub use super::diluc::*;
        pub use super::diona::*;
        pub use super::eula::*;
        pub use super::fatui_pyro_agent::*;
        pub use super::fischl::*;
        pub use super::ganyu::*;
        pub use super::hu_tao::*;
        pub use super::jadeplume_terrorshroom::*;
        pub use super::jean::*;
        pub use super::kaeya::*;
        pub use super::kamisato_ayaka::*;
        pub use super::kamisato_ayato::*;
        pub use super::keqing::*;
        pub use super::klee::*;
        pub use super::kujou_sara::*;
        pub use super::mona::*;
        pub use super::nahida::*;
        pub use super::nilou::*;
        pub use super::ningguang::*;
        pub use super::noelle::*;
        pub use super::qiqi::*;
        pub use super::raiden_shogun::*;
        pub use super::razor::*;
        pub use super::rhodeia_of_loch::*;
        pub use super::sangonomiya_kokomi::*;
        pub use super::shenhe::*;
        pub use super::stonehide_lawachurl::*;
        pub use super::sucrose::*;
        pub use super::tartaglia::*;
        pub use super::tighnari::*;
        pub use super::venti::*;
        pub use super::wanderer::*;
        pub use super::xiangling::*;
        pub use super::xiao::*;
        pub use super::xingqiu::*;
        pub use super::yae_miko::*;
        pub use super::yanfei::*;
        pub use super::yaoyao::*;
        pub use super::yoimiya::*;
        pub use super::zhongli::*;
    };
}

#[macro_export]
#[doc(hidden)]
macro_rules! __generated_enum_cases {
    (CharId, $expr: expr, & $I: ident $(, | $val: ident | $blk: block $(,)?)?) => {
        match $expr {
            CharId::Albedo => $crate::__mapping!(&albedo::$I, $(| $val | $blk)?),
            CharId::Amber => $crate::__mapping!(&amber::$I, $(| $val | $blk)?),
            CharId::AratakiItto => $crate::__mapping!(&arataki_itto::$I, $(| $val | $blk)?),
            CharId::Barbara => $crate::__mapping!(&barbara::$I, $(| $val | $blk)?),
            CharId::Beidou => $crate::__mapping!(&beidou::$I, $(| $val | $blk)?),
            CharId::Bennett => $crate::__mapping!(&bennett::$I, $(| $val | $blk)?),
            CharId::Candace => $crate::__mapping!(&candace::$I, $(| $val | $blk)?),
            CharId::Chongyun => $crate::__mapping!(&chongyun::$I, $(| $val | $blk)?),
            CharId::Collei => $crate::__mapping!(&collei::$I, $(| $val | $blk)?),
            CharId::Cyno => $crate::__mapping!(&cyno::$I, $(| $val | $blk)?),
            CharId::Diluc => $crate::__mapping!(&diluc::$I, $(| $val | $blk)?),
            CharId::Diona => $crate::__mapping!(&diona::$I, $(| $val | $blk)?),
            CharId::Eula => $crate::__mapping!(&eula::$I, $(| $val | $blk)?),
            CharId::FatuiPyroAgent => $crate::__mapping!(&fatui_pyro_agent::$I, $(| $val | $blk)?),
            CharId::Fischl => $crate::__mapping!(&fischl::$I, $(| $val | $blk)?),
            CharId::Ganyu => $crate::__mapping!(&ganyu::$I, $(| $val | $blk)?),
            CharId::HuTao => $crate::__mapping!(&hu_tao::$I, $(| $val | $blk)?),
            CharId::JadeplumeTerrorshroom => $crate::__mapping!(&jadeplume_terrorshroom::$I, $(| $val | $blk)?),
            CharId::Jean => $crate::__mapping!(&jean::$I, $(| $val | $blk)?),
            CharId::Kaeya => $crate::__mapping!(&kaeya::$I, $(| $val | $blk)?),
            CharId::KamisatoAyaka => $crate::__mapping!(&kamisato_ayaka::$I, $(| $val | $blk)?),
            CharId::KamisatoAyato => $crate::__mapping!(&kamisato_ayato::$I, $(| $val | $blk)?),
            CharId::Keqing => $crate::__mapping!(&keqing::$I, $(| $val | $blk)?),
            CharId::Klee => $crate::__mapping!(&klee::$I, $(| $val | $blk)?),
            CharId::KujouSara => $crate::__mapping!(&kujou_sara::$I, $(| $val | $blk)?),
            CharId::Mona => $crate::__mapping!(&mona::$I, $(| $val | $blk)?),
            CharId::Nahida => $crate::__mapping!(&nahida::$I, $(| $val | $blk)?),
            CharId::Nilou => $crate::__mapping!(&nilou::$I, $(| $val | $blk)?),
            CharId::Ningguang => $crate::__mapping!(&ningguang::$I, $(| $val | $blk)?),
            CharId::Noelle => $crate::__mapping!(&noelle::$I, $(| $val | $blk)?),
            CharId::Qiqi => $crate::__mapping!(&qiqi::$I, $(| $val | $blk)?),
            CharId::RaidenShogun => $crate::__mapping!(&raiden_shogun::$I, $(| $val | $blk)?),
            CharId::Razor => $crate::__mapping!(&razor::$I, $(| $val | $blk)?),
            CharId::RhodeiaOfLoch => $crate::__mapping!(&rhodeia_of_loch::$I, $(| $val | $blk)?),
            CharId::SangonomiyaKokomi => $crate::__mapping!(&sangonomiya_kokomi::$I, $(| $val | $blk)?),
            CharId::Shenhe => $crate::__mapping!(&shenhe::$I, $(| $val | $blk)?),
            CharId::StonehideLawachurl => $crate::__mapping!(&stonehide_lawachurl::$I, $(| $val | $blk)?),
            CharId::Sucrose => $crate::__mapping!(&sucrose::$I, $(| $val | $blk)?),
            CharId::Tartaglia => $crate::__mapping!(&tartaglia::$I, $(| $val | $blk)?),
            CharId::Tighnari => $crate::__mapping!(&tighnari::$I, $(| $val | $blk)?),
            CharId::Venti => $crate::__mapping!(&venti::$I, $(| $val | $blk)?),
            CharId::Wanderer => $crate::__mapping!(&wanderer::$I, $(| $val | $blk)?),
            CharId::Xiangling => $crate::__mapping!(&xiangling::$I, $(| $val | $blk)?),
            CharId::Xiao => $crate::__mapping!(&xiao::$I, $(| $val | $blk)?),
            CharId::Xingqiu => $crate::__mapping!(&xingqiu::$I, $(| $val | $blk)?),
            CharId::YaeMiko => $crate::__mapping!(&yae_miko::$I, $(| $val | $blk)?),
            CharId::Yanfei => $crate::__mapping!(&yanfei::$I, $(| $val | $blk)?),
            CharId::Yaoyao => $crate::__mapping!(&yaoyao::$I, $(| $val | $blk)?),
            CharId::Yoimiya => $crate::__mapping!(&yoimiya::$I, $(| $val | $blk)?),
            CharId::Zhongli => $crate::__mapping!(&zhongli::$I, $(| $val | $blk)?),
        }
    };
    (SkillId, $expr: expr, & $I: ident $(, | $val: ident | $blk: block $(,)?)?) => {
        match $expr {
            SkillId::AbiogenesisSolarIsotoma => $crate::__mapping!(&abiogenesis_solar_isotoma::$I, $(| $val | $blk)?),
            SkillId::AdeptusArtHeraldOfFrost => $crate::__mapping!(&adeptus_art_herald_of_frost::$I, $(| $val | $blk)?),
            SkillId::AdeptusArtPreserverOfFortune => $crate::__mapping!(&adeptus_art_preserver_of_fortune::$I, $(| $val | $blk)?),
            SkillId::Akara => $crate::__mapping!(&akara::$I, $(| $val | $blk)?),
            SkillId::AllSchemesToKnow => $crate::__mapping!(&all_schemes_to_know::$I, $(| $val | $blk)?),
            SkillId::AllSchemesToKnowTathata => $crate::__mapping!(&all_schemes_to_know_tathata::$I, $(| $val | $blk)?),
            SkillId::AncientSwordArt => $crate::__mapping!(&ancient_sword_art::$I, $(| $val | $blk)?),
            SkillId::AstableAnemohypostasisCreation6308 => $crate::__mapping!(&astable_anemohypostasis_creation_6308::$I, $(| $val | $blk)?),
            SkillId::BaneOfAllEvil => $crate::__mapping!(&bane_of_all_evil::$I, $(| $val | $blk)?),
            SkillId::BladeAblaze => $crate::__mapping!(&blade_ablaze::$I, $(| $val | $blk)?),
            SkillId::BoltsOfDownfall => $crate::__mapping!(&bolts_of_downfall::$I, $(| $val | $blk)?),
            SkillId::Breastplate => $crate::__mapping!(&breastplate::$I, $(| $val | $blk)?),
            SkillId::CelestialShower => $crate::__mapping!(&celestial_shower::$I, $(| $val | $blk)?),
            SkillId::CeremonialBladework => $crate::__mapping!(&ceremonial_bladework::$I, $(| $val | $blk)?),
            SkillId::ChonghuasLayeredFrost => $crate::__mapping!(&chonghuas_layered_frost::$I, $(| $val | $blk)?),
            SkillId::ClawAndThunder => $crate::__mapping!(&claw_and_thunder::$I, $(| $val | $blk)?),
            SkillId::CloudPartingStar => $crate::__mapping!(&cloud_parting_star::$I, $(| $val | $blk)?),
            SkillId::CuttingTorrent => $crate::__mapping!(&cutting_torrent::$I, $(| $val | $blk)?),
            SkillId::DanceOfAbzendegiDistantDreamsListeningSpring => $crate::__mapping!(&dance_of_abzendegi_distant_dreams_listening_spring::$I, $(| $val | $blk)?),
            SkillId::DanceOfHaftkarsvar => $crate::__mapping!(&dance_of_haftkarsvar::$I, $(| $val | $blk)?),
            SkillId::DanceOfSamser => $crate::__mapping!(&dance_of_samser::$I, $(| $val | $blk)?),
            SkillId::DandelionBreeze => $crate::__mapping!(&dandelion_breeze::$I, $(| $val | $blk)?),
            SkillId::Dawn => $crate::__mapping!(&dawn::$I, $(| $val | $blk)?),
            SkillId::DawnstarPiercer => $crate::__mapping!(&dawnstar_piercer::$I, $(| $val | $blk)?),
            SkillId::Demonbane => $crate::__mapping!(&demonbane::$I, $(| $val | $blk)?),
            SkillId::DivineMaidensDeliverance => $crate::__mapping!(&divine_maidens_deliverance::$I, $(| $val | $blk)?),
            SkillId::DivineMarksmanship => $crate::__mapping!(&divine_marksmanship::$I, $(| $val | $blk)?),
            SkillId::DominusLapidis => $crate::__mapping!(&dominus_lapidis::$I, $(| $val | $blk)?),
            SkillId::DominusLapidisStrikingStone => $crate::__mapping!(&dominus_lapidis_striking_stone::$I, $(| $val | $blk)?),
            SkillId::DoneDeal => $crate::__mapping!(&done_deal::$I, $(| $val | $blk)?),
            SkillId::DoughFu => $crate::__mapping!(&dough_fu::$I, $(| $val | $blk)?),
            SkillId::ExplosivePuppet => $crate::__mapping!(&explosive_puppet::$I, $(| $val | $blk)?),
            SkillId::FantasticVoyage => $crate::__mapping!(&fantastic_voyage::$I, $(| $val | $blk)?),
            SkillId::FashionersTanglevineShaft => $crate::__mapping!(&fashioners_tanglevine_shaft::$I, $(| $val | $blk)?),
            SkillId::FatalRainscreen => $crate::__mapping!(&fatal_rainscreen::$I, $(| $val | $blk)?),
            SkillId::FavoniusBladework => $crate::__mapping!(&favonius_bladework::$I, $(| $val | $blk)?),
            SkillId::FavoniusBladeworkEdel => $crate::__mapping!(&favonius_bladework_edel::$I, $(| $val | $blk)?),
            SkillId::FavoniusBladeworkMaid => $crate::__mapping!(&favonius_bladework_maid::$I, $(| $val | $blk)?),
            SkillId::FavoniusBladeworkWeiss => $crate::__mapping!(&favonius_bladework_weiss::$I, $(| $val | $blk)?),
            SkillId::FeatherSpreading => $crate::__mapping!(&feather_spreading::$I, $(| $val | $blk)?),
            SkillId::FieryRain => $crate::__mapping!(&fiery_rain::$I, $(| $val | $blk)?),
            SkillId::FightClubLegend => $crate::__mapping!(&fight_club_legend::$I, $(| $val | $blk)?),
            SkillId::FireworkFlareUp => $crate::__mapping!(&firework_flare_up::$I, $(| $val | $blk)?),
            SkillId::FloralBrush => $crate::__mapping!(&floral_brush::$I, $(| $val | $blk)?),
            SkillId::ForbiddenCreationIsomer75TypeII => $crate::__mapping!(&forbidden_creation_isomer_75_type_ii::$I, $(| $val | $blk)?),
            SkillId::FoulLegacyRagingTide => $crate::__mapping!(&foul_legacy_raging_tide::$I, $(| $val | $blk)?),
            SkillId::FrostflakeArrow => $crate::__mapping!(&frostflake_arrow::$I, $(| $val | $blk)?),
            SkillId::Frostgnaw => $crate::__mapping!(&frostgnaw::$I, $(| $val | $blk)?),
            SkillId::GaleBlade => $crate::__mapping!(&gale_blade::$I, $(| $val | $blk)?),
            SkillId::GlacialIllumination => $crate::__mapping!(&glacial_illumination::$I, $(| $val | $blk)?),
            SkillId::GlacialWaltz => $crate::__mapping!(&glacial_waltz::$I, $(| $val | $blk)?),
            SkillId::GleamingSpearGuardianStance => $crate::__mapping!(&gleaming_spear_guardian_stance::$I, $(| $val | $blk)?),
            SkillId::GreatSecretArtTenkoKenshin => $crate::__mapping!(&great_secret_art_tenko_kenshin::$I, $(| $val | $blk)?),
            SkillId::GuhuaStyle => $crate::__mapping!(&guhua_style::$I, $(| $val | $blk)?),
            SkillId::GuideToAfterlife => $crate::__mapping!(&guide_to_afterlife::$I, $(| $val | $blk)?),
            SkillId::GuobaAttack => $crate::__mapping!(&guoba_attack::$I, $(| $val | $blk)?),
            SkillId::HanegaSongOfTheWind => $crate::__mapping!(&hanega_song_of_the_wind::$I, $(| $val | $blk)?),
            SkillId::HavocObliteration => $crate::__mapping!(&havoc_obliteration::$I, $(| $val | $blk)?),
            SkillId::HeronStrike => $crate::__mapping!(&heron_strike::$I, $(| $val | $blk)?),
            SkillId::IcetideVortex => $crate::__mapping!(&icetide_vortex::$I, $(| $val | $blk)?),
            SkillId::IcyPaws => $crate::__mapping!(&icy_paws::$I, $(| $val | $blk)?),
            SkillId::IllusoryHeart => $crate::__mapping!(&illusory_heart::$I, $(| $val | $blk)?),
            SkillId::InvokersSpear => $crate::__mapping!(&invokers_spear::$I, $(| $val | $blk)?),
            SkillId::JadeScreen => $crate::__mapping!(&jade_screen::$I, $(| $val | $blk)?),
            SkillId::JumpyDumpty => $crate::__mapping!(&jumpy_dumpty::$I, $(| $val | $blk)?),
            SkillId::Kaboom => $crate::__mapping!(&kaboom::$I, $(| $val | $blk)?),
            SkillId::KamisatoArtHyouka => $crate::__mapping!(&kamisato_art_hyouka::$I, $(| $val | $blk)?),
            SkillId::KamisatoArtKabuki => $crate::__mapping!(&kamisato_art_kabuki::$I, $(| $val | $blk)?),
            SkillId::KamisatoArtKyouka => $crate::__mapping!(&kamisato_art_kyouka::$I, $(| $val | $blk)?),
            SkillId::KamisatoArtMarobashi => $crate::__mapping!(&kamisato_art_marobashi::$I, $(| $val | $blk)?),
            SkillId::KamisatoArtSoumetsu => $crate::__mapping!(&kamisato_art_soumetsu::$I, $(| $val | $blk)?),
            SkillId::KamisatoArtSuiyuu => $crate::__mapping!(&kamisato_art_suiyuu::$I, $(| $val | $blk)?),
            SkillId::KatzleinStyle => $crate::__mapping!(&katzlein_style::$I, $(| $val | $blk)?),
            SkillId::KhandaBarrierBuster => $crate::__mapping!(&khanda_barrier_buster::$I, $(| $val | $blk)?),
            SkillId::KuragesOath => $crate::__mapping!(&kurages_oath::$I, $(| $val | $blk)?),
            SkillId::KyougenFiveCeremonialPlays => $crate::__mapping!(&kyougen_five_ceremonial_plays::$I, $(| $val | $blk)?),
            SkillId::LemniscaticWindCycling => $crate::__mapping!(&lemniscatic_wind_cycling::$I, $(| $val | $blk)?),
            SkillId::LetTheShowBegin => $crate::__mapping!(&let_the_show_begin::$I, $(| $val | $blk)?),
            SkillId::LightningFang => $crate::__mapping!(&lightning_fang::$I, $(| $val | $blk)?),
            SkillId::LiutianArchery => $crate::__mapping!(&liutian_archery::$I, $(| $val | $blk)?),
            SkillId::MajesticDance => $crate::__mapping!(&majestic_dance::$I, $(| $val | $blk)?),
            SkillId::MasatsuZetsugiAkaushiBurst => $crate::__mapping!(&masatsu_zetsugi_akaushi_burst::$I, $(| $val | $blk)?),
            SkillId::MidnightPhantasmagoria => $crate::__mapping!(&midnight_phantasmagoria::$I, $(| $val | $blk)?),
            SkillId::MirrorReflectionOfDoom => $crate::__mapping!(&mirror_reflection_of_doom::$I, $(| $val | $blk)?),
            SkillId::MoonjadeDescent => $crate::__mapping!(&moonjade_descent::$I, $(| $val | $blk)?),
            SkillId::MovoLawa => $crate::__mapping!(&movo_lawa::$I, $(| $val | $blk)?),
            SkillId::NereidsAscension => $crate::__mapping!(&nereids_ascension::$I, $(| $val | $blk)?),
            SkillId::Nightrider => $crate::__mapping!(&nightrider::$I, $(| $val | $blk)?),
            SkillId::NiwabiFireDance => $crate::__mapping!(&niwabi_fire_dance::$I, $(| $val | $blk)?),
            SkillId::Oceanborne => $crate::__mapping!(&oceanborne::$I, $(| $val | $blk)?),
            SkillId::OceanidMimicSummoning => $crate::__mapping!(&oceanid_mimic_summoning::$I, $(| $val | $blk)?),
            SkillId::Origin => $crate::__mapping!(&origin::$I, $(| $val | $blk)?),
            SkillId::PassionOverload => $crate::__mapping!(&passion_overload::$I, $(| $val | $blk)?),
            SkillId::PlamaLawa => $crate::__mapping!(&plama_lawa::$I, $(| $val | $blk)?),
            SkillId::PlanetBefall => $crate::__mapping!(&planet_befall::$I, $(| $val | $blk)?),
            SkillId::Prowl => $crate::__mapping!(&prowl::$I, $(| $val | $blk)?),
            SkillId::Pyronado => $crate::__mapping!(&pyronado::$I, $(| $val | $blk)?),
            SkillId::RainOfStone => $crate::__mapping!(&rain_of_stone::$I, $(| $val | $blk)?),
            SkillId::Raincutter => $crate::__mapping!(&raincutter::$I, $(| $val | $blk)?),
            SkillId::RaphanusSkyCluster => $crate::__mapping!(&raphanus_sky_cluster::$I, $(| $val | $blk)?),
            SkillId::RippleOfFate => $crate::__mapping!(&ripple_of_fate::$I, $(| $val | $blk)?),
            SkillId::RiteOfProgenitureTectonicTide => $crate::__mapping!(&rite_of_progeniture_tectonic_tide::$I, $(| $val | $blk)?),
            SkillId::RoyalDescentBeholdIttoTheEvil => $crate::__mapping!(&royal_descent_behold_itto_the_evil::$I, $(| $val | $blk)?),
            SkillId::RyuukinSaxifrage => $crate::__mapping!(&ryuukin_saxifrage::$I, $(| $val | $blk)?),
            SkillId::SacredRiteHeronsSanctum => $crate::__mapping!(&sacred_rite_herons_sanctum::$I, $(| $val | $blk)?),
            SkillId::SacredRiteWagtailsTide => $crate::__mapping!(&sacred_rite_wagtails_tide::$I, $(| $val | $blk)?),
            SkillId::SacredRiteWolfsSwiftness => $crate::__mapping!(&sacred_rite_wolfs_swiftness::$I, $(| $val | $blk)?),
            SkillId::SealOfApproval => $crate::__mapping!(&seal_of_approval::$I, $(| $val | $blk)?),
            SkillId::SearingOnslaught => $crate::__mapping!(&searing_onslaught::$I, $(| $val | $blk)?),
            SkillId::SecretArtMusouShinsetsu => $crate::__mapping!(&secret_art_musou_shinsetsu::$I, $(| $val | $blk)?),
            SkillId::SecretRiteChasmicSoulfarer => $crate::__mapping!(&secret_rite_chasmic_soulfarer::$I, $(| $val | $blk)?),
            SkillId::SecretSpearOfWangsheng => $crate::__mapping!(&secret_spear_of_wangsheng::$I, $(| $val | $blk)?),
            SkillId::Sharpshooter => $crate::__mapping!(&sharpshooter::$I, $(| $val | $blk)?),
            SkillId::ShiningMiracle => $crate::__mapping!(&shining_miracle::$I, $(| $val | $blk)?),
            SkillId::SignatureMix => $crate::__mapping!(&signature_mix::$I, $(| $val | $blk)?),
            SkillId::SignedEdict => $crate::__mapping!(&signed_edict::$I, $(| $val | $blk)?),
            SkillId::SkywardSonnet => $crate::__mapping!(&skyward_sonnet::$I, $(| $val | $blk)?),
            SkillId::SparklingScatter => $crate::__mapping!(&sparkling_scatter::$I, $(| $val | $blk)?),
            SkillId::SparksNSplash => $crate::__mapping!(&sparks_n_splash::$I, $(| $val | $blk)?),
            SkillId::SpiritSoother => $crate::__mapping!(&spirit_soother::$I, $(| $val | $blk)?),
            SkillId::SpiritfoxSinEater => $crate::__mapping!(&spiritfox_sin_eater::$I, $(| $val | $blk)?),
            SkillId::SpringSpiritSummoning => $crate::__mapping!(&spring_spirit_summoning::$I, $(| $val | $blk)?),
            SkillId::Starshatter => $crate::__mapping!(&starshatter::$I, $(| $val | $blk)?),
            SkillId::StarwardSword => $crate::__mapping!(&starward_sword::$I, $(| $val | $blk)?),
            SkillId::SteelFang => $crate::__mapping!(&steel_fang::$I, $(| $val | $blk)?),
            SkillId::StellarRestoration => $crate::__mapping!(&stellar_restoration::$I, $(| $val | $blk)?),
            SkillId::StellarisPhantasm => $crate::__mapping!(&stellaris_phantasm::$I, $(| $val | $blk)?),
            SkillId::Stormbreaker => $crate::__mapping!(&stormbreaker::$I, $(| $val | $blk)?),
            SkillId::StrikeOfFortune => $crate::__mapping!(&strike_of_fortune::$I, $(| $val | $blk)?),
            SkillId::SubjugationKoukouSendou => $crate::__mapping!(&subjugation_koukou_sendou::$I, $(| $val | $blk)?),
            SkillId::SupplicantsBowmanship => $crate::__mapping!(&supplicants_bowmanship::$I, $(| $val | $blk)?),
            SkillId::Surge => $crate::__mapping!(&surge::$I, $(| $val | $blk)?),
            SkillId::SweepingTime => $crate::__mapping!(&sweeping_time::$I, $(| $val | $blk)?),
            SkillId::TemperedSword => $crate::__mapping!(&tempered_sword::$I, $(| $val | $blk)?),
            SkillId::TenguBowmanship => $crate::__mapping!(&tengu_bowmanship::$I, $(| $val | $blk)?),
            SkillId::TenguStormcall => $crate::__mapping!(&tengu_stormcall::$I, $(| $val | $blk)?),
            SkillId::TheMyriadWilds => $crate::__mapping!(&the_myriad_wilds::$I, $(| $val | $blk)?),
            SkillId::TheShapeOfWater => $crate::__mapping!(&the_shape_of_water::$I, $(| $val | $blk)?),
            SkillId::Thrust => $crate::__mapping!(&thrust::$I, $(| $val | $blk)?),
            SkillId::TideAndTorrent => $crate::__mapping!(&tide_and_torrent::$I, $(| $val | $blk)?),
            SkillId::Tidecaller => $crate::__mapping!(&tidecaller::$I, $(| $val | $blk)?),
            SkillId::TossNTurnSpear => $crate::__mapping!(&toss_n_turn_spear::$I, $(| $val | $blk)?),
            SkillId::TrailOfTheQilin => $crate::__mapping!(&trail_of_the_qilin::$I, $(| $val | $blk)?),
            SkillId::TranscendenceBalefulOmen => $crate::__mapping!(&transcendence_baleful_omen::$I, $(| $val | $blk)?),
            SkillId::TrumpCardKitty => $crate::__mapping!(&trump_card_kitty::$I, $(| $val | $blk)?),
            SkillId::UpaShato => $crate::__mapping!(&upa_shato::$I, $(| $val | $blk)?),
            SkillId::VijnanaPhalaMine => $crate::__mapping!(&vijnana_phala_mine::$I, $(| $val | $blk)?),
            SkillId::VolatileSporeCloud => $crate::__mapping!(&volatile_spore_cloud::$I, $(| $val | $blk)?),
            SkillId::Wavestrider => $crate::__mapping!(&wavestrider::$I, $(| $val | $blk)?),
            SkillId::WhirlwindThrust => $crate::__mapping!(&whirlwind_thrust::$I, $(| $val | $blk)?),
            SkillId::WhisperOfWater => $crate::__mapping!(&whisper_of_water::$I, $(| $val | $blk)?),
            SkillId::WindSpiritCreation => $crate::__mapping!(&wind_spirit_creation::$I, $(| $val | $blk)?),
            SkillId::WindsGrandOde => $crate::__mapping!(&winds_grand_ode::$I, $(| $val | $blk)?),
            SkillId::YakanEvocationSesshouSakura => $crate::__mapping!(&yakan_evocation_sesshou_sakura::$I, $(| $val | $blk)?),
            SkillId::YunlaiSwordsmanship => $crate::__mapping!(&yunlai_swordsmanship::$I, $(| $val | $blk)?),
            SkillId::YuubanMeigen => $crate::__mapping!(&yuuban_meigen::$I, $(| $val | $blk)?),
        }
    };
    (StatusId, $expr: expr, & $I: ident $(, | $val: ident | $blk: block $(,)?)?) => {
        match $expr {
            StatusId::AThousandFloatingDreams => $crate::__mapping!(&a_thousand_floating_dreams::$I, $(| $val | $blk)?),
            StatusId::AdeptalLegacy => $crate::__mapping!(&adeptal_legacy::$I, $(| $val | $blk)?),
            StatusId::AdeptusTemptation => $crate::__mapping!(&adeptus_temptation::$I, $(| $val | $blk)?),
            StatusId::AdventurersBandana => $crate::__mapping!(&adventurers_bandana::$I, $(| $val | $blk)?),
            StatusId::AquilaFavonia => $crate::__mapping!(&aquila_favonia::$I, $(| $val | $blk)?),
            StatusId::ArchaicPetra => $crate::__mapping!(&archaic_petra::$I, $(| $val | $blk)?),
            StatusId::AurousBlaze => $crate::__mapping!(&aurous_blaze::$I, $(| $val | $blk)?),
            StatusId::BlizzardStrayer => $crate::__mapping!(&blizzard_strayer::$I, $(| $val | $blk)?),
            StatusId::BloodBlossom => $crate::__mapping!(&blood_blossom::$I, $(| $val | $blk)?),
            StatusId::Brilliance => $crate::__mapping!(&brilliance::$I, $(| $val | $blk)?),
            StatusId::BrokenRimesEcho => $crate::__mapping!(&broken_rimes_echo::$I, $(| $val | $blk)?),
            StatusId::CatClawShield => $crate::__mapping!(&cat_claw_shield::$I, $(| $val | $blk)?),
            StatusId::CatalyzingField => $crate::__mapping!(&catalyzing_field::$I, $(| $val | $blk)?),
            StatusId::CeremonialGarment => $crate::__mapping!(&ceremonial_garment::$I, $(| $val | $blk)?),
            StatusId::ChakraDesiderata => $crate::__mapping!(&chakra_desiderata::$I, $(| $val | $blk)?),
            StatusId::ChangingShifts => $crate::__mapping!(&changing_shifts::$I, $(| $val | $blk)?),
            StatusId::ChonghuaFrostField => $crate::__mapping!(&chonghua_frost_field::$I, $(| $val | $blk)?),
            StatusId::ColdBloodedStrike => $crate::__mapping!(&cold_blooded_strike::$I, $(| $val | $blk)?),
            StatusId::CrimsonWitchOfFlames => $crate::__mapping!(&crimson_witch_of_flames::$I, $(| $val | $blk)?),
            StatusId::CrowfeatherCover => $crate::__mapping!(&crowfeather_cover::$I, $(| $val | $blk)?),
            StatusId::CryoElementalInfusion => $crate::__mapping!(&cryo_elemental_infusion::$I, $(| $val | $blk)?),
            StatusId::CrystallizeShield => $crate::__mapping!(&crystallize_shield::$I, $(| $val | $blk)?),
            StatusId::DeepwoodMemories => $crate::__mapping!(&deepwood_memories::$I, $(| $val | $blk)?),
            StatusId::DendroCore => $crate::__mapping!(&dendro_core::$I, $(| $val | $blk)?),
            StatusId::ElectroInfusion => $crate::__mapping!(&electro_infusion::$I, $(| $val | $blk)?),
            StatusId::ElementalResonanceFerventFlames => $crate::__mapping!(&elemental_resonance_fervent_flames::$I, $(| $val | $blk)?),
            StatusId::ElementalResonanceShatteringIce => $crate::__mapping!(&elemental_resonance_shattering_ice::$I, $(| $val | $blk)?),
            StatusId::ElementalResonanceSprawlingGreenery => $crate::__mapping!(&elemental_resonance_sprawling_greenery::$I, $(| $val | $blk)?),
            StatusId::ExilesCirclet => $crate::__mapping!(&exiles_circlet::$I, $(| $val | $blk)?),
            StatusId::ExplosiveSpark => $crate::__mapping!(&explosive_spark::$I, $(| $val | $blk)?),
            StatusId::FavoniusSword => $crate::__mapping!(&favonius_sword::$I, $(| $val | $blk)?),
            StatusId::FortunePreservingTalisman => $crate::__mapping!(&fortune_preserving_talisman::$I, $(| $val | $blk)?),
            StatusId::Frozen => $crate::__mapping!(&frozen::$I, $(| $val | $blk)?),
            StatusId::FullPlate => $crate::__mapping!(&full_plate::$I, $(| $val | $blk)?),
            StatusId::GamblersEarrings => $crate::__mapping!(&gamblers_earrings::$I, $(| $val | $blk)?),
            StatusId::GoldenChalicesBounty => $crate::__mapping!(&golden_chalices_bounty::$I, $(| $val | $blk)?),
            StatusId::Grimheart => $crate::__mapping!(&grimheart::$I, $(| $val | $blk)?),
            StatusId::HeartOfDepth => $crate::__mapping!(&heart_of_depth::$I, $(| $val | $blk)?),
            StatusId::HeronShield => $crate::__mapping!(&heron_shield::$I, $(| $val | $blk)?),
            StatusId::IceLotus => $crate::__mapping!(&ice_lotus::$I, $(| $val | $blk)?),
            StatusId::Icicle => $crate::__mapping!(&icicle::$I, $(| $val | $blk)?),
            StatusId::IcyQuill => $crate::__mapping!(&icy_quill::$I, $(| $val | $blk)?),
            StatusId::IllusoryBubble => $crate::__mapping!(&illusory_bubble::$I, $(| $val | $blk)?),
            StatusId::IllusoryTorrent => $crate::__mapping!(&illusory_torrent::$I, $(| $val | $blk)?),
            StatusId::InspirationField => $crate::__mapping!(&inspiration_field::$I, $(| $val | $blk)?),
            StatusId::JadeScreen => $crate::__mapping!(&jade_screen::$I, $(| $val | $blk)?),
            StatusId::JadeShield => $crate::__mapping!(&jade_shield::$I, $(| $val | $blk)?),
            StatusId::KamisatoArtSenho => $crate::__mapping!(&kamisato_art_senho::$I, $(| $val | $blk)?),
            StatusId::LaurelCoronet => $crate::__mapping!(&laurel_coronet::$I, $(| $val | $blk)?),
            StatusId::LeaveItToMe => $crate::__mapping!(&leave_it_to_me::$I, $(| $val | $blk)?),
            StatusId::LingeringAeon => $crate::__mapping!(&lingering_aeon::$I, $(| $val | $blk)?),
            StatusId::LithicSpear => $crate::__mapping!(&lithic_spear::$I, $(| $val | $blk)?),
            StatusId::LotusFlowerCrisp => $crate::__mapping!(&lotus_flower_crisp::$I, $(| $val | $blk)?),
            StatusId::LuckyDogsSilverCirclet => $crate::__mapping!(&lucky_dogs_silver_circlet::$I, $(| $val | $blk)?),
            StatusId::MagicGuide => $crate::__mapping!(&magic_guide::$I, $(| $val | $blk)?),
            StatusId::MaskOfSolitudeBasalt => $crate::__mapping!(&mask_of_solitude_basalt::$I, $(| $val | $blk)?),
            StatusId::MeleeStance => $crate::__mapping!(&melee_stance::$I, $(| $val | $blk)?),
            StatusId::MintyMeatRolls => $crate::__mapping!(&minty_meat_rolls::$I, $(| $val | $blk)?),
            StatusId::MushroomPizza => $crate::__mapping!(&mushroom_pizza::$I, $(| $val | $blk)?),
            StatusId::NiwabiEnshou => $crate::__mapping!(&niwabi_enshou::$I, $(| $val | $blk)?),
            StatusId::NorthernSmokedChicken => $crate::__mapping!(&northern_smoked_chicken::$I, $(| $val | $blk)?),
            StatusId::OrnateKabuto => $crate::__mapping!(&ornate_kabuto::$I, $(| $val | $blk)?),
            StatusId::PactswornPathclearer => $crate::__mapping!(&pactsworn_pathclearer::$I, $(| $val | $blk)?),
            StatusId::ParamitaPapilio => $crate::__mapping!(&paramita_papilio::$I, $(| $val | $blk)?),
            StatusId::Petrification => $crate::__mapping!(&petrification::$I, $(| $val | $blk)?),
            StatusId::PrayerOfTheCrimsonCrown => $crate::__mapping!(&prayer_of_the_crimson_crown::$I, $(| $val | $blk)?),
            StatusId::PyroInfusion => $crate::__mapping!(&pyro_infusion::$I, $(| $val | $blk)?),
            StatusId::Pyronado => $crate::__mapping!(&pyronado::$I, $(| $val | $blk)?),
            StatusId::RadicalVitality => $crate::__mapping!(&radical_vitality::$I, $(| $val | $blk)?),
            StatusId::RagingOniKing => $crate::__mapping!(&raging_oni_king::$I, $(| $val | $blk)?),
            StatusId::RainSword => $crate::__mapping!(&rain_sword::$I, $(| $val | $blk)?),
            StatusId::RainbowBladework => $crate::__mapping!(&rainbow_bladework::$I, $(| $val | $blk)?),
            StatusId::RangedStance => $crate::__mapping!(&ranged_stance::$I, $(| $val | $blk)?),
            StatusId::RavenBow => $crate::__mapping!(&raven_bow::$I, $(| $val | $blk)?),
            StatusId::RightOfFinalInterpretation => $crate::__mapping!(&right_of_final_interpretation::$I, $(| $val | $blk)?),
            StatusId::Riptide => $crate::__mapping!(&riptide::$I, $(| $val | $blk)?),
            StatusId::Rust => $crate::__mapping!(&rust::$I, $(| $val | $blk)?),
            StatusId::SacrificialBow => $crate::__mapping!(&sacrificial_bow::$I, $(| $val | $blk)?),
            StatusId::SacrificialFragments => $crate::__mapping!(&sacrificial_fragments::$I, $(| $val | $blk)?),
            StatusId::SacrificialGreatsword => $crate::__mapping!(&sacrificial_greatsword::$I, $(| $val | $blk)?),
            StatusId::SacrificialSword => $crate::__mapping!(&sacrificial_sword::$I, $(| $val | $blk)?),
            StatusId::Satiated => $crate::__mapping!(&satiated::$I, $(| $val | $blk)?),
            StatusId::ScarletSeal => $crate::__mapping!(&scarlet_seal::$I, $(| $val | $blk)?),
            StatusId::SearingOnslaughtCounter => $crate::__mapping!(&searing_onslaught_counter::$I, $(| $val | $blk)?),
            StatusId::SeedOfSkandha => $crate::__mapping!(&seed_of_skandha::$I, $(| $val | $blk)?),
            StatusId::ShrineOfMaya => $crate::__mapping!(&shrine_of_maya::$I, $(| $val | $blk)?),
            StatusId::SkywardAtlas => $crate::__mapping!(&skyward_atlas::$I, $(| $val | $blk)?),
            StatusId::SkywardHarp => $crate::__mapping!(&skyward_harp::$I, $(| $val | $blk)?),
            StatusId::SkywardPride => $crate::__mapping!(&skyward_pride::$I, $(| $val | $blk)?),
            StatusId::SkywardSpine => $crate::__mapping!(&skyward_spine::$I, $(| $val | $blk)?),
            StatusId::SparksNSplash => $crate::__mapping!(&sparks_n_splash::$I, $(| $val | $blk)?),
            StatusId::Sprout => $crate::__mapping!(&sprout::$I, $(| $val | $blk)?),
            StatusId::Stealth => $crate::__mapping!(&stealth::$I, $(| $val | $blk)?),
            StatusId::StoneForce => $crate::__mapping!(&stone_force::$I, $(| $val | $blk)?),
            StatusId::Stonehide => $crate::__mapping!(&stonehide::$I, $(| $val | $blk)?),
            StatusId::Stormzone => $crate::__mapping!(&stormzone::$I, $(| $val | $blk)?),
            StatusId::SuperlativeSuperstrength => $crate::__mapping!(&superlative_superstrength::$I, $(| $val | $blk)?),
            StatusId::SweepingTime => $crate::__mapping!(&sweeping_time::$I, $(| $val | $blk)?),
            StatusId::TakimeguriKanka => $crate::__mapping!(&takimeguri_kanka::$I, $(| $val | $blk)?),
            StatusId::TenkoThunderbolts => $crate::__mapping!(&tenko_thunderbolts::$I, $(| $val | $blk)?),
            StatusId::TheWolfWithin => $crate::__mapping!(&the_wolf_within::$I, $(| $val | $blk)?),
            StatusId::ThunderSummonersCrown => $crate::__mapping!(&thunder_summoners_crown::$I, $(| $val | $blk)?),
            StatusId::ThunderbeastsTarge => $crate::__mapping!(&thunderbeasts_targe::$I, $(| $val | $blk)?),
            StatusId::ThunderingFury => $crate::__mapping!(&thundering_fury::$I, $(| $val | $blk)?),
            StatusId::TidecallerSurfEmbrace => $crate::__mapping!(&tidecaller_surf_embrace::$I, $(| $val | $blk)?),
            StatusId::TravelersHandySword => $crate::__mapping!(&travelers_handy_sword::$I, $(| $val | $blk)?),
            StatusId::TravelingDoctorsHandkerchief => $crate::__mapping!(&traveling_doctors_handkerchief::$I, $(| $val | $blk)?),
            StatusId::UndividedHeart => $crate::__mapping!(&undivided_heart::$I, $(| $val | $blk)?),
            StatusId::VijnanaSuffusion => $crate::__mapping!(&vijnana_suffusion::$I, $(| $val | $blk)?),
            StatusId::ViridescentVenerer => $crate::__mapping!(&viridescent_venerer::$I, $(| $val | $blk)?),
            StatusId::ViridescentVenerersDiadem => $crate::__mapping!(&viridescent_venerers_diadem::$I, $(| $val | $blk)?),
            StatusId::WhenTheCraneReturned => $crate::__mapping!(&when_the_crane_returned::$I, $(| $val | $blk)?),
            StatusId::WhiteIronGreatsword => $crate::__mapping!(&white_iron_greatsword::$I, $(| $val | $blk)?),
            StatusId::WhiteTassel => $crate::__mapping!(&white_tassel::$I, $(| $val | $blk)?),
            StatusId::Windfavored => $crate::__mapping!(&windfavored::$I, $(| $val | $blk)?),
            StatusId::WineStainedTricorne => $crate::__mapping!(&wine_stained_tricorne::$I, $(| $val | $blk)?),
            StatusId::WitchsScorchingHat => $crate::__mapping!(&witchs_scorching_hat::$I, $(| $val | $blk)?),
            StatusId::WolfsGravestone => $crate::__mapping!(&wolfs_gravestone::$I, $(| $val | $blk)?),
            StatusId::YakshasMask => $crate::__mapping!(&yakshas_mask::$I, $(| $val | $blk)?),
        }
    };
    (SummonId, $expr: expr, & $I: ident $(, | $val: ident | $blk: block $(,)?)?) => {
        match $expr {
            SummonId::BakeKurage => $crate::__mapping!(&bake_kurage::$I, $(| $val | $blk)?),
            SummonId::BaronBunny => $crate::__mapping!(&baron_bunny::$I, $(| $val | $blk)?),
            SummonId::BountifulCore => $crate::__mapping!(&bountiful_core::$I, $(| $val | $blk)?),
            SummonId::BurningFlame => $crate::__mapping!(&burning_flame::$I, $(| $val | $blk)?),
            SummonId::ClusterbloomArrow => $crate::__mapping!(&clusterbloom_arrow::$I, $(| $val | $blk)?),
            SummonId::CuileinAnbar => $crate::__mapping!(&cuilein_anbar::$I, $(| $val | $blk)?),
            SummonId::DandelionField => $crate::__mapping!(&dandelion_field::$I, $(| $val | $blk)?),
            SummonId::DrunkenMist => $crate::__mapping!(&drunken_mist::$I, $(| $val | $blk)?),
            SummonId::EyeOfStormyJudgment => $crate::__mapping!(&eye_of_stormy_judgment::$I, $(| $val | $blk)?),
            SummonId::FrostflakeSekiNoTo => $crate::__mapping!(&frostflake_seki_no_to::$I, $(| $val | $blk)?),
            SummonId::GardenOfPurity => $crate::__mapping!(&garden_of_purity::$I, $(| $val | $blk)?),
            SummonId::Guoba => $crate::__mapping!(&guoba::$I, $(| $val | $blk)?),
            SummonId::HeraldOfFrost => $crate::__mapping!(&herald_of_frost::$I, $(| $val | $blk)?),
            SummonId::LargeWindSpirit => $crate::__mapping!(&large_wind_spirit::$I, $(| $val | $blk)?),
            SummonId::LightfallSword => $crate::__mapping!(&lightfall_sword::$I, $(| $val | $blk)?),
            SummonId::MelodyLoop => $crate::__mapping!(&melody_loop::$I, $(| $val | $blk)?),
            SummonId::OceanidMimicFrog => $crate::__mapping!(&oceanid_mimic_frog::$I, $(| $val | $blk)?),
            SummonId::OceanidMimicRaptor => $crate::__mapping!(&oceanid_mimic_raptor::$I, $(| $val | $blk)?),
            SummonId::OceanidMimicSquirrel => $crate::__mapping!(&oceanid_mimic_squirrel::$I, $(| $val | $blk)?),
            SummonId::Oz => $crate::__mapping!(&oz::$I, $(| $val | $blk)?),
            SummonId::Reflection => $crate::__mapping!(&reflection::$I, $(| $val | $blk)?),
            SummonId::SacredCryoPearl => $crate::__mapping!(&sacred_cryo_pearl::$I, $(| $val | $blk)?),
            SummonId::SesshouSakura => $crate::__mapping!(&sesshou_sakura::$I, $(| $val | $blk)?),
            SummonId::SolarIsotoma => $crate::__mapping!(&solar_isotoma::$I, $(| $val | $blk)?),
            SummonId::StoneStele => $crate::__mapping!(&stone_stele::$I, $(| $val | $blk)?),
            SummonId::Stormeye => $crate::__mapping!(&stormeye::$I, $(| $val | $blk)?),
            SummonId::TalismanSpirit => $crate::__mapping!(&talisman_spirit::$I, $(| $val | $blk)?),
            SummonId::TenguJuuraiAmbush => $crate::__mapping!(&tengu_juurai_ambush::$I, $(| $val | $blk)?),
            SummonId::TenguJuuraiStormcluster => $crate::__mapping!(&tengu_juurai_stormcluster::$I, $(| $val | $blk)?),
            SummonId::Ushi => $crate::__mapping!(&ushi::$I, $(| $val | $blk)?),
            SummonId::YueguiThrowingMode => $crate::__mapping!(&yuegui_throwing_mode::$I, $(| $val | $blk)?),
        }
    };
    (SupportId, $expr: expr, & $I: ident $(, | $val: ident | $blk: block $(,)?)?) => {
        match $expr {
            SupportId::DawnWinery => $crate::__mapping!(&dawn_winery::$I, $(| $val | $blk)?),
            SupportId::FavoniusCathedral => $crate::__mapping!(&favonius_cathedral::$I, $(| $val | $blk)?),
            SupportId::IronTongueTian => $crate::__mapping!(&iron_tongue_tian::$I, $(| $val | $blk)?),
            SupportId::JadeChamber => $crate::__mapping!(&jade_chamber::$I, $(| $val | $blk)?),
            SupportId::Katheryne => $crate::__mapping!(&katheryne::$I, $(| $val | $blk)?),
            SupportId::KnightsOfFavoniusLibrary => $crate::__mapping!(&knights_of_favonius_library::$I, $(| $val | $blk)?),
            SupportId::Liben => $crate::__mapping!(&liben::$I, $(| $val | $blk)?),
            SupportId::LiuSu => $crate::__mapping!(&liu_su::$I, $(| $val | $blk)?),
            SupportId::LiyueHarborWharf => $crate::__mapping!(&liyue_harbor_wharf::$I, $(| $val | $blk)?),
            SupportId::Paimon => $crate::__mapping!(&paimon::$I, $(| $val | $blk)?),
            SupportId::SangonomiyaShrine => $crate::__mapping!(&sangonomiya_shrine::$I, $(| $val | $blk)?),
            SupportId::Tenshukaku => $crate::__mapping!(&tenshukaku::$I, $(| $val | $blk)?),
            SupportId::Timaeus => $crate::__mapping!(&timaeus::$I, $(| $val | $blk)?),
            SupportId::Tubby => $crate::__mapping!(&tubby::$I, $(| $val | $blk)?),
            SupportId::Wagner => $crate::__mapping!(&wagner::$I, $(| $val | $blk)?),
            SupportId::WangshuInn => $crate::__mapping!(&wangshu_inn::$I, $(| $val | $blk)?),
        }
    };
    (CardId, $expr: expr, & $I: ident $(, | $val: ident | $blk: block $(,)?)?) => {
        match $expr {
            CardId::AThousandFloatingDreams => $crate::__mapping!(&a_thousand_floating_dreams::$I, $(| $val | $blk)?),
            CardId::AdeptusTemptation => $crate::__mapping!(&adeptus_temptation::$I, $(| $val | $blk)?),
            CardId::AdventurersBandana => $crate::__mapping!(&adventurers_bandana::$I, $(| $val | $blk)?),
            CardId::AquilaFavonia => $crate::__mapping!(&aquila_favonia::$I, $(| $val | $blk)?),
            CardId::ArchaicPetra => $crate::__mapping!(&archaic_petra::$I, $(| $val | $blk)?),
            CardId::Beneficent => $crate::__mapping!(&beneficent::$I, $(| $val | $blk)?),
            CardId::BlankCard => $crate::__mapping!(&blank_card::$I, $(| $val | $blk)?),
            CardId::BlizzardStrayer => $crate::__mapping!(&blizzard_strayer::$I, $(| $val | $blk)?),
            CardId::BrokenRimesEcho => $crate::__mapping!(&broken_rimes_echo::$I, $(| $val | $blk)?),
            CardId::CalxsArts => $crate::__mapping!(&calxs_arts::$I, $(| $val | $blk)?),
            CardId::ChangingShifts => $crate::__mapping!(&changing_shifts::$I, $(| $val | $blk)?),
            CardId::ColdBloodedStrike => $crate::__mapping!(&cold_blooded_strike::$I, $(| $val | $blk)?),
            CardId::CrimsonWitchOfFlames => $crate::__mapping!(&crimson_witch_of_flames::$I, $(| $val | $blk)?),
            CardId::Crossfire => $crate::__mapping!(&crossfire::$I, $(| $val | $blk)?),
            CardId::DawnWinery => $crate::__mapping!(&dawn_winery::$I, $(| $val | $blk)?),
            CardId::DeepwoodMemories => $crate::__mapping!(&deepwood_memories::$I, $(| $val | $blk)?),
            CardId::DescentOfDivinity => $crate::__mapping!(&descent_of_divinity::$I, $(| $val | $blk)?),
            CardId::ElementalResonanceFerventFlames => $crate::__mapping!(&elemental_resonance_fervent_flames::$I, $(| $val | $blk)?),
            CardId::ElementalResonanceHighVoltage => $crate::__mapping!(&elemental_resonance_high_voltage::$I, $(| $val | $blk)?),
            CardId::ElementalResonanceShatteringIce => $crate::__mapping!(&elemental_resonance_shattering_ice::$I, $(| $val | $blk)?),
            CardId::ElementalResonanceSprawlingGreenery => $crate::__mapping!(&elemental_resonance_sprawling_greenery::$I, $(| $val | $blk)?),
            CardId::ElementalResonanceWovenFlames => $crate::__mapping!(&elemental_resonance_woven_flames::$I, $(| $val | $blk)?),
            CardId::ElementalResonanceWovenIce => $crate::__mapping!(&elemental_resonance_woven_ice::$I, $(| $val | $blk)?),
            CardId::ElementalResonanceWovenStone => $crate::__mapping!(&elemental_resonance_woven_stone::$I, $(| $val | $blk)?),
            CardId::ElementalResonanceWovenThunder => $crate::__mapping!(&elemental_resonance_woven_thunder::$I, $(| $val | $blk)?),
            CardId::ElementalResonanceWovenWaters => $crate::__mapping!(&elemental_resonance_woven_waters::$I, $(| $val | $blk)?),
            CardId::ElementalResonanceWovenWeeds => $crate::__mapping!(&elemental_resonance_woven_weeds::$I, $(| $val | $blk)?),
            CardId::ElementalResonanceWovenWinds => $crate::__mapping!(&elemental_resonance_woven_winds::$I, $(| $val | $blk)?),
            CardId::ExilesCirclet => $crate::__mapping!(&exiles_circlet::$I, $(| $val | $blk)?),
            CardId::FavoniusCathedral => $crate::__mapping!(&favonius_cathedral::$I, $(| $val | $blk)?),
            CardId::FavoniusSword => $crate::__mapping!(&favonius_sword::$I, $(| $val | $blk)?),
            CardId::FloralSidewinder => $crate::__mapping!(&floral_sidewinder::$I, $(| $val | $blk)?),
            CardId::FlowingFlame => $crate::__mapping!(&flowing_flame::$I, $(| $val | $blk)?),
            CardId::GamblersEarrings => $crate::__mapping!(&gamblers_earrings::$I, $(| $val | $blk)?),
            CardId::GloriousSeason => $crate::__mapping!(&glorious_season::$I, $(| $val | $blk)?),
            CardId::GrandExpectation => $crate::__mapping!(&grand_expectation::$I, $(| $val | $blk)?),
            CardId::HeartOfDepth => $crate::__mapping!(&heart_of_depth::$I, $(| $val | $blk)?),
            CardId::IGotYourBack => $crate::__mapping!(&i_got_your_back::$I, $(| $val | $blk)?),
            CardId::IHaventLostYet => $crate::__mapping!(&i_havent_lost_yet::$I, $(| $val | $blk)?),
            CardId::IronTongueTian => $crate::__mapping!(&iron_tongue_tian::$I, $(| $val | $blk)?),
            CardId::JadeChamber => $crate::__mapping!(&jade_chamber::$I, $(| $val | $blk)?),
            CardId::KantenSenmyouBlessing => $crate::__mapping!(&kanten_senmyou_blessing::$I, $(| $val | $blk)?),
            CardId::Katheryne => $crate::__mapping!(&katheryne::$I, $(| $val | $blk)?),
            CardId::KeenSight => $crate::__mapping!(&keen_sight::$I, $(| $val | $blk)?),
            CardId::KnightsOfFavoniusLibrary => $crate::__mapping!(&knights_of_favonius_library::$I, $(| $val | $blk)?),
            CardId::KyoukaFuushi => $crate::__mapping!(&kyouka_fuushi::$I, $(| $val | $blk)?),
            CardId::LandsOfDandelion => $crate::__mapping!(&lands_of_dandelion::$I, $(| $val | $blk)?),
            CardId::LaurelCoronet => $crate::__mapping!(&laurel_coronet::$I, $(| $val | $blk)?),
            CardId::LeaveItToMe => $crate::__mapping!(&leave_it_to_me::$I, $(| $val | $blk)?),
            CardId::Liben => $crate::__mapping!(&liben::$I, $(| $val | $blk)?),
            CardId::LightningStiletto => $crate::__mapping!(&lightning_stiletto::$I, $(| $val | $blk)?),
            CardId::LithicSpear => $crate::__mapping!(&lithic_spear::$I, $(| $val | $blk)?),
            CardId::LiuSu => $crate::__mapping!(&liu_su::$I, $(| $val | $blk)?),
            CardId::LotusFlowerCrisp => $crate::__mapping!(&lotus_flower_crisp::$I, $(| $val | $blk)?),
            CardId::LuckyDogsSilverCirclet => $crate::__mapping!(&lucky_dogs_silver_circlet::$I, $(| $val | $blk)?),
            CardId::MaskOfSolitudeBasalt => $crate::__mapping!(&mask_of_solitude_basalt::$I, $(| $val | $blk)?),
            CardId::MintyMeatRolls => $crate::__mapping!(&minty_meat_rolls::$I, $(| $val | $blk)?),
            CardId::MondstadtHashBrown => $crate::__mapping!(&mondstadt_hash_brown::$I, $(| $val | $blk)?),
            CardId::MushroomPizza => $crate::__mapping!(&mushroom_pizza::$I, $(| $val | $blk)?),
            CardId::MysticalAbandon => $crate::__mapping!(&mystical_abandon::$I, $(| $val | $blk)?),
            CardId::NaganoharaMeteorSwarm => $crate::__mapping!(&naganohara_meteor_swarm::$I, $(| $val | $blk)?),
            CardId::NorthernSmokedChicken => $crate::__mapping!(&northern_smoked_chicken::$I, $(| $val | $blk)?),
            CardId::OrnateKabuto => $crate::__mapping!(&ornate_kabuto::$I, $(| $val | $blk)?),
            CardId::PaidInFull => $crate::__mapping!(&paid_in_full::$I, $(| $val | $blk)?),
            CardId::Paimon => $crate::__mapping!(&paimon::$I, $(| $val | $blk)?),
            CardId::PoundingSurprise => $crate::__mapping!(&pounding_surprise::$I, $(| $val | $blk)?),
            CardId::ProphecyOfSubmersion => $crate::__mapping!(&prophecy_of_submersion::$I, $(| $val | $blk)?),
            CardId::QuickKnit => $crate::__mapping!(&quick_knit::$I, $(| $val | $blk)?),
            CardId::RightOfFinalInterpretation => $crate::__mapping!(&right_of_final_interpretation::$I, $(| $val | $blk)?),
            CardId::Rust => $crate::__mapping!(&rust::$I, $(| $val | $blk)?),
            CardId::SacrificialBow => $crate::__mapping!(&sacrificial_bow::$I, $(| $val | $blk)?),
            CardId::SacrificialFragments => $crate::__mapping!(&sacrificial_fragments::$I, $(| $val | $blk)?),
            CardId::SacrificialGreatsword => $crate::__mapping!(&sacrificial_greatsword::$I, $(| $val | $blk)?),
            CardId::SacrificialSword => $crate::__mapping!(&sacrificial_sword::$I, $(| $val | $blk)?),
            CardId::SangonomiyaShrine => $crate::__mapping!(&sangonomiya_shrine::$I, $(| $val | $blk)?),
            CardId::SanguineRouge => $crate::__mapping!(&sanguine_rouge::$I, $(| $val | $blk)?),
            CardId::SendOff => $crate::__mapping!(&send_off::$I, $(| $val | $blk)?),
            CardId::ShakenNotPurred => $crate::__mapping!(&shaken_not_purred::$I, $(| $val | $blk)?),
            CardId::SkywardAtlas => $crate::__mapping!(&skyward_atlas::$I, $(| $val | $blk)?),
            CardId::SkywardHarp => $crate::__mapping!(&skyward_harp::$I, $(| $val | $blk)?),
            CardId::SkywardPride => $crate::__mapping!(&skyward_pride::$I, $(| $val | $blk)?),
            CardId::SkywardSpine => $crate::__mapping!(&skyward_spine::$I, $(| $val | $blk)?),
            CardId::Starsigns => $crate::__mapping!(&starsigns::$I, $(| $val | $blk)?),
            CardId::SteadyBreathing => $crate::__mapping!(&steady_breathing::$I, $(| $val | $blk)?),
            CardId::StrategicReserve => $crate::__mapping!(&strategic_reserve::$I, $(| $val | $blk)?),
            CardId::Strategize => $crate::__mapping!(&strategize::$I, $(| $val | $blk)?),
            CardId::SweetMadame => $crate::__mapping!(&sweet_madame::$I, $(| $val | $blk)?),
            CardId::Tenshukaku => $crate::__mapping!(&tenshukaku::$I, $(| $val | $blk)?),
            CardId::TheBestestTravelCompanion => $crate::__mapping!(&the_bestest_travel_companion::$I, $(| $val | $blk)?),
            CardId::TheOverflow => $crate::__mapping!(&the_overflow::$I, $(| $val | $blk)?),
            CardId::TheScentRemained => $crate::__mapping!(&the_scent_remained::$I, $(| $val | $blk)?),
            CardId::TheStarrySkiesTheirFlowersRain => $crate::__mapping!(&the_starry_skies_their_flowers_rain::$I, $(| $val | $blk)?),
            CardId::ThunderSummonersCrown => $crate::__mapping!(&thunder_summoners_crown::$I, $(| $val | $blk)?),
            CardId::ThunderingFury => $crate::__mapping!(&thundering_fury::$I, $(| $val | $blk)?),
            CardId::ThunderingPenance => $crate::__mapping!(&thundering_penance::$I, $(| $val | $blk)?),
            CardId::Timaeus => $crate::__mapping!(&timaeus::$I, $(| $val | $blk)?),
            CardId::TravelersHandySword => $crate::__mapping!(&travelers_handy_sword::$I, $(| $val | $blk)?),
            CardId::TravelingDoctorsHandkerchief => $crate::__mapping!(&traveling_doctors_handkerchief::$I, $(| $val | $blk)?),
            CardId::Tubby => $crate::__mapping!(&tubby::$I, $(| $val | $blk)?),
            CardId::UndividedHeart => $crate::__mapping!(&undivided_heart::$I, $(| $val | $blk)?),
            CardId::ViridescentVenerer => $crate::__mapping!(&viridescent_venerer::$I, $(| $val | $blk)?),
            CardId::ViridescentVenerersDiadem => $crate::__mapping!(&viridescent_venerers_diadem::$I, $(| $val | $blk)?),
            CardId::Wagner => $crate::__mapping!(&wagner::$I, $(| $val | $blk)?),
            CardId::WangshuInn => $crate::__mapping!(&wangshu_inn::$I, $(| $val | $blk)?),
            CardId::WhenTheCraneReturned => $crate::__mapping!(&when_the_crane_returned::$I, $(| $val | $blk)?),
            CardId::WineStainedTricorne => $crate::__mapping!(&wine_stained_tricorne::$I, $(| $val | $blk)?),
            CardId::WishesUnnumbered => $crate::__mapping!(&wishes_unnumbered::$I, $(| $val | $blk)?),
            CardId::WitchsScorchingHat => $crate::__mapping!(&witchs_scorching_hat::$I, $(| $val | $blk)?),
            CardId::WolfsGravestone => $crate::__mapping!(&wolfs_gravestone::$I, $(| $val | $blk)?),
        }
    };
}
